version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: boba-cafe-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./images:/app/images  # Mount the images directory for persistent storage
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 